version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_INTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 10s
      retries: 10

  cqrs-consumer:
    build: .
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092  # ← Используйте внутренний порт
      DB_USER: user
      DB_PASSWORD: secret
      DB_HOST: postgres
      DB_NAME: social
    depends_on:
      kafka:
        condition: service_healthy
    command: ["python", "cqrs_consumer.py"]

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      kafka:
        condition: service_healthy
    command: 
      - /bin/sh
      - -c
      - |
        kafka-topics --create --topic post_events \
        --bootstrap-server kafka:9092 \
        --replication-factor 1 \
        --partitions 1
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  user-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      SERVICE: user
      DB_USER: user
      DB_PASSWORD: secret
      DB_HOST: postgres
      DB_NAME: social
      JWT_SECRET: super-secret-key
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
    restart: on-failure

  wall-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      SERVICE: wall
      DB_USER: user
      DB_PASSWORD: secret
      DB_HOST: postgres
      DB_NAME: social
      JWT_SECRET: super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  message-service:
    build: .
    ports:
      - "5002:5002"
    environment:
      SERVICE: message
      MONGO_HOST: mongo
      JWT_SECRET: super-secret-key
    depends_on:
      mongo:
        condition: service_started
    restart: on-failure

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: social
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/02-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d social"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
      - ./init_mongo.js:/docker-entrypoint-initdb.d/init.js
    restart: always

volumes:
  postgres_data:
  mongo_data:
  redis_data: